### ISSUE TITLE
Custom hashing does not work as expected (rename this gnn)

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof-solph#336]
@ckaldemeyer: Sorry for hijacking this comment, but I'd like to keep this issue as uncluttered as possible at the start. So for transparency: this is @gnn speaking from here on.

This causes the objects stored in an energy system and the ones used as keys in a results dictionary to ["desynchronise"](https://github.com/oemof/oemof/blob/e2a011a847dcc0ff035d2d2a7205111ed0250d02/examples/solph/csv_reader/investment/investment.py#L124-L131) when unpickling a results dictionary from disc. The actual problem is, that unpickling a results dictionary creates new instances of the objects used as keys in the dictionary. This means that the objects now have a different `id` which in turn means they have a different `label`.
The solution is simple: don't generate the `label` dynamically whenever it is accessed, but generate it statically on construction.
I'm going to push that soon, so that https://github.com/oemof/oemof/pull/329#issuecomment-332516442 isn't blocked by this issue.

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/pull/329#issuecomment-332516442

**Comment by uvchik** [comment]
@ckaldemeyer and @gnn I think this is fixed, isn't it?

**Comment by gnn** [comment]
I don't think this is blocking anything right now, so I'm removing the `urgent` tag. IIRC the problem still persists and I will take care of it, but for `0.2.1`.

**Comment by jnnr** [comment]
The initial message is a bit confusing. Is this still an issue?

**Comment by p-snft** [comment]
Seems not to be an issue anymore.
