### ISSUE TITLE
CBC (and other AMPL solvers) are not linked correctly anymore

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof-solph#928]
Specifically, the link provided here does not point to the intended location anymore: https://oemof-solph.readthedocs.io/en/latest/readme.html#installing-a-solver.

Now, `amplpy` needs to be installed and can deliver `cbc` and others. I tested it on my machine, however pyomo refuses to find the executable after having it installed with `amplpy`. I cannot really look deep into it currently, just wanted to raise awareness :).

**Comment by p-snft** [comment]
Solved in dev.

**Comment by JulianBarinton** [comment]
Dear oemof community, 
on my machine (windows 11) cbc still cannot be found neither installed via the respective cbc repo (https://github.com/coin-or/Cbc/releases) nor installed via amply. I have tried it for oemof.solph version dev, 0.5, and 0.4.5. What is the recommendable way to go to solve this problem? May we please update the documentation accordingly?

Cheers Julian

**Comment by p-snft** [comment]
Hi Julian, you should be able to download CBC (probably the MSVC version), extract it and add it to PATH. There is no automated installation routine.

**Comment by JulianBarinton** [comment]
Dear Patrik, thank you for coming back to me on this one. I downloaded the cbc, extracted it, and added it to the path, but unfortunately oemof.solph cannot find it. CBC worked for me on windows 10, but not on windows 11 (I have changed my laptop). GLPK works also on windows 11, but has some performance issues. Did anyone else similar issues and found a way to solve it?

Cheers Julian

**Comment by p-snft** [comment]
Definitely not being a Windows expert, I see no reason why cbc should not be found if it's in PATH. Could you test if cbc is found in your CMD and also check the content of your PATH? (The command `path` in the command line should print it according to some online references.)

PS: It helps if you open an issue instead of commenting a solved one.
